# Default settings (Local Development)
spring:
  profiles:
    active: dev

  # ==========================================
  # THIS IS THE MISSING EMAIL CONFIGURATION!
  # ==========================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL@gmail.com
    password: YOUR_16_CHARACTER_APP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration mapping
jwt:
  secret: ${JWT_SECRET:your-super-secret-key-your-super-secret-key-which-must-be-long-enough}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# STRIPE CONFIGURATION
stripe:
  api:
    key: sk_test_51Te9s0F1MT8HJYfLI3RacncjP5j2fhfc09mmCtyuY3XJ8h8ZzAxzd0BfG72N9IZvcGCCzqAZbwcxcwMKyr8k89yb0083dBxaB0
---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "manas@9546"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
# Production Profile (Render)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update