server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "manas@9546"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  secret: 123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 Hours
  refresh-expiration: 604800000 # 7 Days

logging:
  level:
    root: INFO
    com.carrental: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG